### ISSUE TITLE
Addition of functions

### ISSUE THREAD

**Issue by kkadatoka** [dudanogueira/rocketconnect.cookiecutter#9]
1. Is it possible to add a selection for rocket chat port (instead of 3000)
2. Can we explicitly request rocket image version (instead of latest)
3. Similarly request for mongo version (say 5.0).

**Comment by dudanogueira** [comment]
we could :) but that would probably polute the initial config. I am doing a clean up and will only leave essentials.

I think it's already easy enough to just edit the outcome docker yaml and go from there.

Thanks for the suggestion, anyway!
